// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjt8Ti3e5_ErscUx5C6ec5kSLUplNxkac',
    appId: '1:799317703660:web:a669a23d88085b2ad49ec9',
    messagingSenderId: '799317703660',
    projectId: 'tiktok-clone-9a518',
    authDomain: 'tiktok-clone-9a518.firebaseapp.com',
    storageBucket: 'tiktok-clone-9a518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvFDirExupKer9X5uP4Gy3LxmVHPJdKM',
    appId: '1:799317703660:android:10f5d83b753f3d6cd49ec9',
    messagingSenderId: '799317703660',
    projectId: 'tiktok-clone-9a518',
    storageBucket: 'tiktok-clone-9a518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaPdQnnvrubccPyh1vXA0LpCPXG_UpZTY',
    appId: '1:799317703660:ios:e2973ae34173acd3d49ec9',
    messagingSenderId: '799317703660',
    projectId: 'tiktok-clone-9a518',
    storageBucket: 'tiktok-clone-9a518.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
